version: '3'

services:

  mysql-db:
    image: mysql:latest
    env_file: docker.env
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always


  backend:
    build:
      context: ./ 
      dockerfile: ./docker/backend/Dockerfile 
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/app 
      - /usr/app/node_modules 
    env_file: docker.env
      

  frontend:
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "8880:80"
    volumes:
      - ./frontend:/usr/app