version: '3'

services:

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: passpass
      MYSQL_DATABASE: mewsic_sql
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./  # Modification du chemin du contexte
      dockerfile: ./docker/backend/Dockerfile  # Correction du chemin du Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/app # Montez le répertoire du backend pour permettre les mises à jour en temps réel
      - /usr/app/node_modules # Volume anonyme pour node_modules seulement
    environment:
      DATABASE_USER: root
      DATABASE: mewsic_sql
      DATABASE_PASSWORD: passpass
      DATABASE_HOST: mysql-db 
      

  frontend:
    build:
      context: ./  # Modification du chemin du contexte
      dockerfile: ./docker/frontend/Dockerfile  # Correction du chemin du Dockerfile
    ports:
      - "8880:80"
    volumes:
      - ./frontend:/usr/app # Montez le répertoire du frontend pour permettre les mises à jour en temps réel