version: '3'

services:

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: passpass
      MYSQL_DATABASE: mewsic_sql
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always


  backend:
    build:
      context: ./ 
      dockerfile: ./docker/backend/Dockerfile 
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/app 
      - /usr/app/node_modules 
    environment:
      DATABASE_USER: root
      DATABASE: mewsic_sql
      DATABASE_PASSWORD: passpass
      DATABASE_HOST: mysql-db 
      

  frontend:
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "8880:80"
    volumes:
      - ./frontend:/usr/app